version: '3.8'

services:
  db:
    image: postgres:16
    container_name: sanicpay_db
    restart: always
    environment:
      POSTGRES_DB: sanicpay
      POSTGRES_USER: sanic
      POSTGRES_PASSWORD: sanicpassword
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sanic"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: sanicpay_app
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+asyncpg://sanic:sanicpassword@db:5432/sanicpay
    ports:
      - "8000:8000"
    command: ["/bin/sh", "-c", "alembic upgrade head && python server.py"]

volumes:
  pg_data:
